name: SimpleVision
version: "${version}"
description: "A simple & configurable nightvision plugin."
main: org.creativecraft.simplevision.SimpleVisionPlugin
softdepend: [PlaceholderAPI]
api-version: 1.18
